trigger:
  - feature/92556-setup-spm
  - main

pool:
  vmImage: macos-latest

steps:
  - checkout: self
    clean: true
    lfs: true
    displayName: Clone repository

  - script: swift package resolve
    failOnStderr: true
    displayName: swift package resolve

  - script: swift build --build-tests
    failOnStderr: true
    displayName: swift build tests

  - script: swift test
# setting failOnStderr: true will cause failure
# because 'swift test' writes content to stderr
#  failOnStderr: true
    displayName: swift test